### ISSUE TITLE
Archive Request - Series Type Parameter not working

### ISSUE THREAD

**Issue by cmdigital** [SeanoNET/FroniusSolarClient#2]
SeriesType Parameter needs to be named in Query string in order to work. (Currently being ignored)

Proposed fix:
InverterArchiveDataService.cs
Line 51

`return $"?Scope={scope}&StartDate={startDate.ToString("d.M.yyyy")}&EndDate={endDate.ToString("d.M.yyyy")}&HumanReadable={humanReadable.ToString()}&SeriesType={seriesType.ToString()}{deviceClassParam}" + $"&{channelParam}";`

        }

**Comment by SeanoNET** [comment]
Hi @cmdigital 

Thanks for pointing this out, I will take a look at this in the next few days, I am also happy to review a PR in the meantime.

**Comment by SeanoNET** [comment]
Hi @cmdigital - solved in [0.4.0](https://github.com/SeanoNET/FroniusSolarClient/releases/tag/0.4.0)

Thanks for contributing!
