### ISSUE TITLE
P_Grid and P_Load not integers

### ISSUE THREAD

**Issue by cmdigital** [SeanoNET/FroniusSolarClient#3]
When not integer values in the response these two properties (P_Grid and P_Load) generate an error. 

Defining them as decimal solves the issue. Proposed fix:

In PowerFlowRealtimeData.cs

`        [JsonProperty("P_Grid")]
        public **decimal** PGrid { get; set; }

        /// <summary>
        /// This value is null if no meter is enabled ( + generator, - consumer ) 
        /// </summary>
        [JsonProperty("P_Load")]
        public **decimal** PLoad { get; set; }
`

**Comment by SeanoNET** [comment]
Hi @cmdigital - this has been solved in [0.4.0](https://github.com/SeanoNET/FroniusSolarClient/releases/tag/0.4.0)

Thanks for contributing! 👍

**Comment by cmdigital** [comment]
Thank you!
