### ISSUE TITLE
FroniusSolarClient.SolarClient[0]: An error occured: Input string 'xx.xxxxx' is not a valid integer. Path 'Body.Data.Site.rel_SelfConsumption', line 24, position 54.

### ISSUE THREAD

**Issue by MowedMeadow** [SeanoNET/FroniusSolarClient#4]
Hi,

I'm confronted with this error message, when trying to GetPowerFlowRealtimeData() of my Fronius Symo 15.0-3-M. Fetching other data like GetCommonInverterData() works fine. I'm using version 0.4.0 of the package within an ASP.Net Core (.net5) application. Probably it has something to do with the firmware version of the Inverter? I updated the firmware just yesterday to version 3.18.7-1.
Any other ideas?

Thank you very much!
Patrick

**Comment by MowedMeadow** [comment]
Changed rel_SelfConsumption property to an decimal, the request response is OK now. Thanks!

**Comment by SeanoNET** [comment]
Hey @MowedMeadow, great find! I have fixed this in [v0.5.3](https://github.com/SeanoNET/FroniusSolarClient/releases/tag/v0.5.3)

**Comment by MowedMeadow** [comment]
Same need at RelAutonomy property :) Thanks!

**Comment by SeanoNET** [comment]
Fixed and released in [v5.4.0](https://github.com/SeanoNET/FroniusSolarClient/releases/tag/v0.5.4) 🙂
